package site

import (
	_ "embed"
	"fmt"
	"html/template"
	"math"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/neolao/batocera-scrap-manager/internal/gamelist"
	"github.com/neolao/batocera-scrap-manager/internal/registry"
)

//go:embed style.css
var styleCSS string

// StyleSheet is the theme shared by every HTML rendering of the registry —
// the static site generated by Generate and the pages served by the web UI
// — so a visual change applies to both at once. It carries the layout
// building blocks common to them (theme variables, header, sticky system
// navigation, card grid, responsive rules) and nothing specific to either.
var StyleSheet = template.CSS(styleCSS)

// SystemView groups one system's games for rendering.
type SystemView struct {
	Name  string
	Games []GameView
}

// GameView wraps a gamelist.Game with fields precomputed for rendering: its
// registry identifier and system, properly percent-encoded media paths (left
// empty when the file is missing from the registry folder), and a
// human-readable rating and release year — so templates stay free of
// formatting logic.
type GameView struct {
	gamelist.Game
	ID            string
	System        string
	ImagePath     string
	VideoPath     string
	MarqueePath   string
	ThumbnailPath string
	Stars         string
	RatingLabel   string
	Year          string
}

// EscapeMediaPath builds a relative URL from system and a media path (as
// found in gamelist.xml), percent-encoding each path segment. Go's
// html/template contextual auto-escaping deliberately leaves reserved
// characters such as '[' and ']' untouched in URL attributes, which some
// HTTP servers mishandle; encoding them explicitly here avoids that.
func EscapeMediaPath(system, relPath string) string {
	segments := strings.Split(system+"/"+relPath, "/")
	for i, seg := range segments {
		segments[i] = url.PathEscape(seg)
	}
	return strings.Join(segments, "/")
}

// filledStars converts a gamelist rating (a decimal string between 0 and 1)
// into a number of filled stars out of five, reporting whether the rating
// was usable at all.
func filledStars(rating string) (int, bool) {
	r, err := strconv.ParseFloat(rating, 64)
	if err != nil {
		return 0, false
	}
	if r < 0 {
		r = 0
	}
	if r > 1 {
		r = 1
	}
	return int(math.Round(r * 5)), true
}

// FormatStars renders a gamelist rating (a decimal string between 0 and 1)
// as a 5-star string, or an empty string if rating is missing or invalid.
func FormatStars(rating string) string {
	filled, ok := filledStars(rating)
	if !ok {
		return ""
	}
	return strings.Repeat("★", filled) + strings.Repeat("☆", 5-filled)
}

// formatRatingLabel renders the same rating as FormatStars in words ("4/5"),
// so the value is not conveyed by star glyphs alone — which a screen reader
// announces poorly or not at all. It returns an empty string for a missing
// or invalid rating.
func formatRatingLabel(rating string) string {
	filled, ok := filledStars(rating)
	if !ok {
		return ""
	}
	return fmt.Sprintf("%d/5", filled)
}

// FormatYear extracts the year from a gamelist release date
// (EmulationStation's "YYYYMMDDTHHMMSS" format), or an empty string if
// releaseDate is missing or does not start with a 4-digit year.
func FormatYear(releaseDate string) string {
	if len(releaseDate) < 4 {
		return ""
	}
	year := releaseDate[:4]
	for _, c := range year {
		if c < '0' || c > '9' {
			return ""
		}
	}
	return year
}

// MediaFileExists reports whether the media file referenced by a game's
// Image/Video/Marquee/Thumbnail field actually exists at
// <registryFolder>/<system>/<relPath>. A game's metadata can reference a
// file that is missing from the registry folder (partial scrape, manual
// cleanup, etc.); linking to it anyway would produce a broken image/video in
// the browser instead of the placeholder.
func MediaFileExists(registryFolder, system, relPath string) bool {
	info, err := os.Stat(filepath.Join(registryFolder, system, filepath.FromSlash(relPath)))
	return err == nil && !info.IsDir()
}

// GroupBySystem groups entries by system, sorted by system name and then by
// game name within each system, for deterministic output.
func GroupBySystem(entries []registry.Entry, registryFolder string) []SystemView {
	bySystem := map[string][]gamelist.Game{}
	for _, e := range entries {
		bySystem[e.System] = append(bySystem[e.System], e.Game)
	}

	names := make([]string, 0, len(bySystem))
	for name := range bySystem {
		names = append(names, name)
	}
	sort.Strings(names)

	systems := make([]SystemView, 0, len(names))
	for _, name := range names {
		games := bySystem[name]
		sort.Slice(games, func(i, j int) bool { return games[i].Name < games[j].Name })

		views := make([]GameView, len(games))
		for i, g := range games {
			views[i] = newGameView(g, name, registryFolder)
		}
		systems = append(systems, SystemView{Name: name, Games: views})
	}
	return systems
}

// newGameView precomputes g's rendering fields, resolving each of its media
// references to a percent-encoded path only when the file is actually
// present under registryFolder.
func newGameView(g gamelist.Game, system, registryFolder string) GameView {
	view := GameView{
		Game:        g,
		ID:          registry.GameID(g.Path),
		System:      system,
		Stars:       FormatStars(g.Rating),
		RatingLabel: formatRatingLabel(g.Rating),
		Year:        FormatYear(g.ReleaseDate),
	}

	mediaPaths := []struct {
		relPath string
		into    *string
	}{
		{g.Image, &view.ImagePath},
		{g.Video, &view.VideoPath},
		{g.Marquee, &view.MarqueePath},
		{g.Thumbnail, &view.ThumbnailPath},
	}
	for _, media := range mediaPaths {
		if media.relPath != "" && MediaFileExists(registryFolder, system, media.relPath) {
			*media.into = EscapeMediaPath(system, media.relPath)
		}
	}
	return view
}
